### ISSUE TITLE
Create new BitMap resource from scratch

### ISSUE THREAD

**Issue by rosshadden** [webcatzz/godot-bitmap-editor#1]
I was hoping this would let me create a new `BitMap` resource from scratch, but if it does I have yet to figure out how. I get the attached errors about the width being 0. Which is of course true, when you create a new BitMap it is 0x0. In the screenshot of this plugin I saw a size editor though so I was hoping I would simply be able to change it from 0x0.
![image](https://github.com/user-attachments/assets/b54b2a95-e743-4485-b3ea-3875f285253a)

**Comment by rawsp33d** [comment]
Ummm I didn't enable the plugin :facepalm:. Sorry for the noise!
